name: ecommerce_application
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  badges: ^2.0.1
  flutter_bloc: ^7.3.0
  google_maps_flutter: ^2.0.9
  syncfusion_flutter_charts: ^19.3.44+1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Lobster
      fonts:
        - asset: lib/Asset/Fonts/Lobster/Lobster-Regular.ttf
  assets:
    - lib/Asset/Images/avtphi.jpg
    - lib/Asset/Images/background1.png
    - lib/Asset/Images/background2.png
    - lib/Asset/Images/background3.png
    - lib/Asset/Images/background4.png
    - lib/Asset/Images/background5.jpg
    - lib/Asset/Images/boom.png
    - lib/Asset/Images/user1.jpg
    - lib/Asset/Images/user2.jpg
    - lib/Asset/Images/user3.jpg
    - lib/Asset/Images/user4.jpg
    - lib/Asset/Images/user5.jpg
    - lib/Asset/Images/user6.jpg
    - lib/Asset/Images/user7.jpg
    - lib/Asset/Images/user8.jpg
    - lib/Asset/Images/user9.jpg
    - lib/Asset/Images/user10.jpg
    - lib/Asset/Images/Discover1.jpg
    - lib/Asset/Images/Discover2.jpg
    - lib/Asset/Images/Discover3.jpg
    - lib/Asset/Images/Discover4.jpg
    - lib/Asset/Images/Discover5.jpg
    - lib/Asset/Images/Discover6.jpg
    - lib/Asset/Images/Discover7.jpg
    - lib/Asset/Images/Discover8.jpg
    - lib/Asset/Images/Discover9.jpg
    - lib/Asset/Images/Discover10.jpg
    - lib/Asset/Images/s1.jpg
    - lib/Asset/Images/s2.jpg
    - lib/Asset/Images/s3.jpg
    - lib/Asset/Images/s4.jpg
    - lib/Asset/Images/s5.jpg
    - lib/Asset/Images/s6.jpg
    - lib/Asset/Images/s7.jpg
    - lib/Asset/Images/s8.jpg
    - lib/Asset/Images/s9.jpg
    - lib/Asset/Images/s10.jpg
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

        
    